/**
* My API
* This is the API
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 *  * @param id  * @param name  * @param displayName  * @param shortDisplayName  * @param description */
data class Key (    val id: java.util.UUID,    val name: kotlin.String,    val displayName: kotlin.String,    val shortDisplayName: kotlin.String,    val description: kotlin.String
) {
}
